### ISSUE TITLE
Issue with latest version of semantic-release

### ISSUE THREAD

**Issue by jeffijoe** [elliotttf/semantic-release-conventional-commits#9]
Hey, thanks for this awesome plugin!

It seems to break with the latest version though. Here's the stack trace:

```
An error occurred while running semantic-release: TypeError: cb is not a function
    at module.exports (/home/travis/build/jeffijoe/awilix-koa/node_modules/semantic-release-conventional-commits/index.js:43:3)
    at Object.analyzeCommits (/home/travis/build/jeffijoe/awilix-koa/node_modules/semantic-release/lib/plugins/normalize.js:27:26)
    at module.exports (/home/travis/build/jeffijoe/awilix-koa/node_modules/semantic-release/index.js:37:30)
```

**Comment by elliotttf** [comment]
Thanks for the report! I'll try to get a fix in this week, but feel free to open a PR if you need it sooner 😄

**Comment by jeffijoe** [comment]
Take your time! I disabled the plugin for now. 😄

**Comment by jeffijoe** [comment]
Thanks! 🎊
